/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    Column: typeof import('primevue/column')['default']
    D3Graph: typeof import('./src/components/graph/D3Graph.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    ErrorDialog: typeof import('./src/components/ErrorDialog.vue')['default']
    GraphWrapper: typeof import('./src/components/graph/GraphWrapper.vue')['default']
    HelpButton: typeof import('./src/components/HelpButton.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Menu: typeof import('primevue/menu')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Panel: typeof import('primevue/panel')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    QuickNav: typeof import('./src/components/layout/QuickNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/layout/SearchBar.vue')['default']
    SearchItem: typeof import('./src/components/search/SearchItem.vue')['default']
    SearchItemList: typeof import('./src/components/search/SearchItemList.vue')['default']
    SearchSettings: typeof import('./src/components/search/SearchSettings.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SpotlightBlock: typeof import('./src/components/spotlight/SpotlightBlock.vue')['default']
    SpotlightSection: typeof import('./src/components/spotlight/SpotlightSection.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TrendResultsList: typeof import('./src/components/trends/TrendResultsList.vue')['default']
    TrendSettings: typeof import('./src/components/trends/TrendSettings.vue')['default']
  }
}
