services:

    database:
        image: timescale/timescaledb:latest-pg16
        restart: unless-stopped
        shm_size: 2gb
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=woordwacht
            - READER_PASSWORD=${READER_PASSWORD}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - database:/var/lib/postgresql/data
            - ./database/init_db:/docker-entrypoint-initdb.d/
            - ./database/postgresql.conf:/etc/postgres/postgresql.conf
        command: "-c 'config_file=/etc/postgres/postgresql.conf'"

    server:
        image: woordwacht/server:${VERSION_LABEL}
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - READER_PASSWORD=${READER_PASSWORD}
            - READER_USER=${READER_USER}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
        build:
            context: server
        restart: unless-stopped
        ports:
            - '8000:8000'

    client:
        image: woordwacht/client:${VERSION_LABEL}
        build:
            context: client
        restart: unless-stopped
        ports:
            - '80:8080'

volumes:
    database:
