services:

    database:
        image: timescale/timescaledb:2.18.1-pg17
        restart: unless-stopped
        shm_size: 2gb
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - READER_USER=${READER_USER}
            - READER_PASSWORD=${READER_PASSWORD}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - database:/var/lib/postgresql/data
            - ./database/init_db:/docker-entrypoint-initdb.d/
            - ./database/postgresql.conf:/etc/postgres/postgresql.conf
        command: "-c 'config_file=/etc/postgres/postgresql.conf'"
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
            interval: 3s
            timeout: 5s
            retries: 5

    builder:
        image: timescale/timescaledb:2.18.1-pg17
        restart: unless-stopped
        shm_size: 2gb
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - READER_USER=${READER_USER}
            - READER_PASSWORD=${READER_PASSWORD}
        ports:
            - '${BUILDER_PORT}:5432'
        volumes:
            - builder:/var/lib/postgresql/data
            - ./database/init_db:/docker-entrypoint-initdb.d/
            - ./database/postgresql.conf:/etc/postgres/postgresql.conf
        command: "-c 'config_file=/etc/postgres/postgresql.conf'"
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
            interval: 3s
            timeout: 5s
            retries: 5

    server:
        image: instituutnederlandsetaal/woordpeiler-server:${VERSION_LABEL}
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=database # Always refer to the database container
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - READER_USER=${READER_USER}
            - READER_PASSWORD=${READER_PASSWORD}
        build:
            context: server
        restart: unless-stopped

    client:
        image: instituutnederlandsetaal/woordpeiler-client:${VERSION_LABEL}
        build:
            context: client
        restart: unless-stopped

    proxy:
        image: nginx:1.27.4-alpine3.21
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - client
            - server
        ports:
            - "80:80"
        restart: unless-stopped

volumes:
    database:
        name: ${DATABASE_VOLUME}
    builder:
        name: ${BUILDER_VOLUME}
