services:
    database:
        image: timescale/timescaledb:latest-pg16
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=woordwacht
            - READER_PASSWORD=${READER_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - database:/var/lib/postgresql/data
            - ./database/init:/docker-entrypoint-initdb.d/
    server:
        image: woordwacht/server
        build:
            context: server
        restart: always
        ports:
            - '8000:8000'

    client:
        image: woordwacht/client
        build:
            context: client
        restart: always
        ports:
            - '5173:5173'
volumes:
    database:
