services:
    database:
        image: timescale/timescaledb:latest-pg16
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=woordwacht
        ports:
            - '5432:5432'
        volumes:
            - database:/var/lib/postgresql/data
volumes:
    database:
